apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: "{{ .Release.Name }}-secrets-provider"
spec:
  provider: azure
  secretObjects:
  - secretName: "{{ .Release.Name }}-secrets"
    type: Opaque
    data:
    {{- range .Values.handledSecrets }}
    - objectName: {{ .key | quote }}
      key: {{ .key | quote }}
    {{- end }}
  parameters:
    keyvaultName: {{ .Values.vault.name | quote }}
    usePodIdentity: "true"
    objects: |
      array:
      {{- range .Values.handledSecrets }}
      - |
        objectName: {{ .key | quote }}
        objectType: secret
      {{- end }}
    tenantId: {{ .Values.azure.tenant | quote }}
